  - name: Configure config file
    ansible.builtin.templated:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
    
  - name: Installing mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: latest

  - name: Update listen address
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Enabling  mongodb
    ansible.builtin.service:
      name: mongod
      enabled: yes
  
  - name: Restart mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted