- name: install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: python




- name: install node-exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter.yml