- name: setup elastic.repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: changes is filebeat yml file
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: restart filebeat
  ansible.builtin.service:
    service: filebeat
    state: restarted
    enabled: yes