
- name: setup logstash config file
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: restart service
  ansible.builtin.systemd:
    service: logstash
    state: restarted
