

- name: Configure config file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo


- name: Installing nodejs
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed


- name: Load schema
  ansible.builtin.shell:  mongo --host mongodb-dev.devopspractice.store </$app_path/schema/{{ component }}.js