
#- name: copy mongo repo file
#  ansible.builtin.copy:
#    src: mongo.repo
#    dest: /etc/yum.repos.d/mongo.repo

#- name: copy mongodb repo file
#  ansible.builtin.copy:
#    src: mongodb.repo
#    dest: /etc/yum.repos.d/mongodb.repo
#
#- name: Installing nodejs
#  ansible.builtin.yum:
#    name: mongodb-org-shell
#    state: installed
#
#
#- name: Load schema
#  ansible.builtin.shell:  mongo --host mongodb-dev.devopspractice.store </app/schema/{{ component }}.js

- name: Copy MongoDB Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  #ansible.builtin.shell: mongo --host mongodb-dev.devopspractice.store </app/schema/{{ component }}.js
  ansible.builtin.shell:  mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', 'roboshop.{{ env }}.{{component}}.docdb_endpoint', region="us-east-1")}}:27017 --sslCAFile global-bundle.pem --username {{ lookup('amazon.aws.aws_ssm', 'roboshop.{{ env }}.docdb.username', region="us-east-1")}} --password {{ lookup('amazon.aws.aws_ssm', 'roboshop.{{ env }}.docdb.password', region="us-east-1")}} </app/schema/{{ component }}.js

